name: Scheduled Merge Upstream Action
on: 
  schedule:
    - cron: '0 * * * *'

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0 
      - name: Merge Upstream
        run: | 
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote add upstream ssh://git@github.com:kbsec/CS-501-2021.git
          git fetch upstream
          git merge upstream/main main
          git push origin
        shell: bash

